# Generated by Django 4.2.7 on 2023-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_payments_options_course_owner_lesson_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/img/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='видео'),
        ),
    ]
