# Generated by Django 4.2.7 on 2024-01-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_price_lesson_price_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='sessions_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
