# Generated by Django 4.2.7 on 2024-01-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_payments_sessions_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
