# Generated by Django 4.2.7 on 2024-01-06 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_payments_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата оплаты'),
        ),
    ]
