# Generated by Django 4.2.7 on 2024-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_payments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='sessions_url',
            field=models.CharField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
